### ISSUE TITLE
Windows installer issues

### ISSUE THREAD

**Issue by nebbian** [nebbian/RoboxSlicerExtension#29]
After going through the code, it looks like the installer doesn't handle separate files for different OS's.  

At least, I couldn't figure out where it would grab the current CuraEngine.exe from when installing on windows.

Contributing to this is the difficulty in testing an installer that always grabs files from the master branch...

Can someone (@natdan?) let me know how to modify the installer, so that it installs CuraEngine.exe instead of CuraEngine?  And also let me know where to put my updated version of CuraEngine.exe so that it will be installed when someone runs the installer?

Thanks.

**Comment by natdan** [comment]
I'll try to do some work tomorrow evening... I might have done it but failed to upload it :(

**Comment by natdan** [comment]
OK. It should work now! :) I've split InstallationFile enum to Linux, OSX and Windows variants. Please give it a go - it should work now (at least it did on text run on my VM Windows - and host OSX :) )

**Comment by nebbian** [comment]
Good stuff @natdan, much appreciated.  I just need confirmation on the CuraEngine.cmd file (ie it's not needed, so it shouldn't be in the installer), and I can then push this branch to master.  This should then let people on Windows try it out :)
